### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by herbygillot** [LyonSyonII/hunt-rs#3]
Can you add and specify which license `hunt` is available under?

**Comment by omasanori** [comment]
Yes, I assume it is MIT OR Apache-2.0: https://github.com/LyonSyonII/hunt-rs/blob/8aabea050b368c01275cddea73574d6a77d1a692/Cargo.toml#L8 but I also think adding license files or note in README is better.

**Comment by herbygillot** [comment]
Thank you all.
